---
title: "R Notebook"
output: html_notebook
---

```{r}
library(plot3D)

```

```{r}
gen_sphere <- function(grid_pts = 80, radius = 1) {
  M <- mesh(seq(0, 2*pi, length.out = 80),
            seq(-pi/2, pi/2, length.out = 80))
  u <- M$x ; v <- M$y
  x <- cos(v) * cos(u)
  y <- cos(v) * sin(u)
  z <- sin(v)
  list(
    x = x,
    y = y,
    z = z
  )
}

move_sphere <- function(S, x_c, y_c, z_c) {
  S$x <- S$x + x_c
  S$y <- S$y + y_c
  S$z <- S$z + z_c
  return(S)
}

vector_sphere <- function(S) {
  data.frame(
    x = as.vector(S$x),
    y = as.vector(S$y),
    z = as.vector(S$z)
  )
}

flatten_spheres <- function(...) {
  L <- list(...)
  L <- lapply(L, vector_sphere)
  do.call(rbind, L)
}

```

```{r}
S <- gen_sphere()
SL <- move_sphere(S,-1, 0, 0)
SR <- move_sphere(S, 1, 0, 0)
SB <- move_sphere(S, 0, -sqrt(3), 0)
ST <- move_sphere(S, 0, -(1/sqrt(3)), 1.5)

S_pts <- flatten_spheres(SL, SR, SB, ST)

```

```{r}
lim <- c(-5,5)

x1 <- c(   0, -7,  7,  0)
y1 <- c(-0.9,  5,  5, -9)
z1 <- c(   8, -2, -2, -2)

M1 <- data.frame(
  x = x1,
  y = y1,
  z = z1
)

polygon_pts <- function(x1,y1,z1) {
  c1 <- c(1,2,3)
  c2 <- c(1,2,4)
  c3 <- c(1,3,4)
  c4 <- c(2,3,4)
  list(
    x = c(x1[c1], NA, x1[c2], NA, x1[c3], NA, x1[c4]),
    y = c(y1[c1], NA, y1[c2], NA, y1[c3], NA, y1[c4]),
    z = c(z1[c1], NA, z1[c2], NA, z1[c3], NA, z1[c4])
  )
}

M2 <- polygon_pts(x1, y1, z1)

# M1 <- mesh(x1,y1,z1)

max(convhulln(rbind(M1, S_pts)))

```

```{r}
sphere_plot <- function(SL, SR, SB, ST, M1, M2) {
 
  {scatter3D(SL$x, SL$y, SL$z, colvar = SL$z, 
         col = ramp.col(col = c("black", "pink")),
         colkey = FALSE,
         xlim = lim, ylim = lim, zlim = lim,
         phi = 65, theta = 80)
  scatter3D(SR$x, SR$y, SR$z, colvar = SR$z, 
         col = ramp.col(col = c("black", "pink")),
         colkey = FALSE,
         add = TRUE)
  scatter3D(SB$x, SB$y, SB$z, colvar = SB$z, 
         col = ramp.col(col = c("black", "pink")),
         colkey = FALSE,
         add = TRUE)
  scatter3D(ST$x, ST$y, ST$z, colvar = ST$z, 
         col = ramp.col(col = c("black", "pink")),
         colkey = FALSE,
         add = TRUE)
  polygon3D(M2$x, M2$y, M2$z, colvar = c(4:1),
            col = ramp.col(col = c("navy", "cyan"), alpha = 0.1),
            colkey = FALSE,
            border = "black",
            add = TRUE)
  scatter3D(M1$x, M1$y, M1$z, colvar = M1$z,
            colkey = FALSE,
            add = TRUE)
  }
 
}

sphere_plot(SL, SR, SB, ST, M1, M2)

```

```{r}
volume <- function(M) {
  mat <- array(c(M$x, M$y, M$z, rep(1,4)), dim = c(4,4))
  vol <- (1/factorial(3)) * det(mat)
  return(abs(vol))
}

volume(M1)
```

```{r}

p <- M1[2:4,c(3,1,2)]

area(p) * 10 / 3

```

```{r}
check_points <- function(s, m) {
  s_rows <- dim(s)[1]
  m_rows <- dim(m)[1]
  pts <- m
  pts[(m_rows+1):(m_rows+s_rows),] <- s
  hull <- convhulln(pts)
  return(max(hull) <= m_rows)
}

check_points(S_pts, M1)

tmp <- M1
tmp[1,] <- c(0,0,0)

check_points(S_pts, tmp)

```

```{r}

sim_anneal <- function(s_pts, m, rounds) {
  # browser()
  start_temp <- 4
  temp <- start_temp
  history <- m
  history$t <- 0L
  history$vol <- volume(m)
  history$temp <- start_temp
  history$check <- TRUE
  history$prb_keep <- 1
  history$keep <- TRUE
  for (t in 1:rounds) {
    old_vol <- volume(m)
    new_m <- m + rnorm(6)*temp/start_temp
    new_vol <- volume(new_m)
    # probability of keeping new pts
    if (new_vol < old_vol) {
      prb_keep <- 1
    } else {
      prb_keep <- exp((old_vol - new_vol) / temp)
    }
    check <- check_points(s_pts, new_m)
    if (!check) prb_keep <- 0
    # keep/discard
    if (runif(1) < prb_keep) {
      m <- new_m
      keep <- TRUE
    } else {keep <- FALSE}
    # record keeping
    new_history <- new_m
    new_history$t <- t
    new_history$vol <- new_vol
    new_history$temp <- temp
    new_history$check <- check
    new_history$prb_keep <- prb_keep
    new_history$keep <- keep
    history <- rbind(history, new_history)
    # temp <- temp - (start_temp / rounds) # linear
    temp <- temp * 0.999 # exponential
    if (t %% 200 == 0) cat(paste0(t,"."))
    # if (TRUE) cat(paste0(t,"."))
  }
  return(history)
}

res <- sim_anneal(S_pts, M1, 1000)

```

























